apiVersion: v1
kind: Service
metadata:
    name: react-frontend
    labels:
        app: react-frontend
spec:
    type: NodePort
    selector:
        app: react-frontend
    ports:
    -   name: http
        protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 31000