apiVersion: v1
kind: Service
metadata:
    name: react-frontend
    labels:
        app: react-frontend
spec:
    type: LoadBalancer
    selector:
        app: react-frontend
    ports:
    -   name: http
        port: 80
        targetPort: 80